---
# tasks file for kubernetes specific packages

# Microk8s
- name: Install microk8s
  become: yes
  snap:
    name: microk8s
    classic: yes

# Kubectl install - https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management
- name: Install kubectl
  block:
    - name: Install kubectl dependencies
      become: yes
      apt:
        name: "{{ kubectl_packages_dependencies }}"
        state: latest

    - name: Get google apt key
      become: yes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add kubernetes apt repository
      become: yes
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        filename: kubernetes

    - name: Install kubectl 
      become: yes
      apt:
        name: kubectl
        state: latest

# Helm package installation - https://helm.sh/docs/intro/install/#from-apt-debianubuntu
- name: Install Helm
  block:
    - name: Get baltocdn apt key
      become: yes
      apt_key:
        url: https://baltocdn.com/helm/signing.asc

    - name: Add helm apt repository
      become: yes
      apt_repository:
        repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
        filename: helm

    - name: Install helm 
      become: yes
      apt:
        name: helm
        state: latest

# TODO: check local version
- name: Install latest velero version
  become: yes
  unarchive:
    src: "https://github.com/vmware-tanzu/velero/releases/download/v{{ velero_version }}/velero-v{{ velero_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    extra_opts:
      - --strip=1
      - --wildcards
      - '*/velero'
    remote_src: yes

# TODO: check local version
- name: Install latest tekton version
  become: yes
  unarchive:
    src: "https://github.com/tektoncd/cli/releases/download/v{{ tekton_version }}/tkn_{{ tekton_version }}_Linux_x86_64.tar.gz"
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    extra_opts:
      - tkn
    remote_src: yes

# TODO: check local version
- name: Install latest k9s version
  become: yes
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_x86_64.tar.gz"
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    extra_opts:
      - k9s
    remote_src: yes

- name: Install octant
  become: yes
  apt:
   deb: "https://github.com/vmware-tanzu/octant/releases/download/v{{ octant_version }}/octant_{{ octant_version }}_Linux-64bit.deb"