---
# tasks file for packages

- name: Upgrade all packages to the latest version
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes

# Snap repository - https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html
- name: Allow snap installation
  become: yes
  file:
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent

# Debian standard packages
- name: Install {{ apt_packages }}
  become: yes
  apt:
    name: "{{ apt_packages }}"
    state: latest

# Python packages
- name: Install {{ pip_packages }}
  pip:
    name: "{{ item }}"
    state: latest
  loop: "{{ pip_packages }}"

# Terraform package installation - https://www.terraform.io/docs/cli/install/apt.html
- name: Install Hashicorp packages
  block:
    - name: Get Hashicorp apt key
      become: yes
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: Add Hashicorp apt repository
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
        filename: hashicorp

    - name: Install {{ hashicorp_packages }}
      become: yes
      apt:
        name: "{{ hashicorp_packages }}"
        state: latest

# Kubernetes packages
- include: kubernetes.yml

# VS Code
- include: vscode.yml