---
# defaults file for packages
packages:
  - ccze
  - git
  - htop
  - ncdu
  - rsync
  - screen
  - tcpdump
  - vim
  - zsh

packages_kubectl_dependencies:
  - apt-transport-https
  - curl
  - gnupg2

velero_version: "1.5.2"
tekton_version: "0.15.0"